#!/bin/bash
# gen_inference_config.sh — Ω4: 生成正确的推理 job config (可执行 > 可记忆)
# 内嵌所有 OMEGA_LESSONS 中的硬约束，避免人工/AI写YAML犯错
#
# Usage: bash gcp/gen_inference_config.sh <checkpoint_gcs_path> <output_gcs_path> [options]
# Example:
#   bash gcp/gen_inference_config.sh \
#     gs://omega-pure-data/checkpoints/phase10_softmax_v5/best.pt \
#     gs://omega-pure-data/phase10/phase10_predictions.parquet \
#     --hd 64 --wt 32 --ws 4 --spot

set -euo pipefail

# Parse args
CHECKPOINT="${1:?Usage: bash gcp/gen_inference_config.sh <checkpoint> <output> [--hd N] [--wt N] [--ws N] [--spot]}"
OUTPUT="${2:?Usage: bash gcp/gen_inference_config.sh <checkpoint> <output> [--hd N] [--wt N] [--ws N] [--spot]}"
shift 2

HD=64; WT=32; WS=4; BS=512; SPOT=false; CKPT_INTERVAL=50
while [[ $# -gt 0 ]]; do
    case $1 in
        --hd) HD="$2"; shift 2;;
        --wt) WT="$2"; shift 2;;
        --ws) WS="$2"; shift 2;;
        --bs) BS="$2"; shift 2;;
        --spot) SPOT=true; shift;;
        *) echo "Unknown arg: $1"; exit 1;;
    esac
done

DOCKER_TAG=$(tail -n 20 gcp/manifest.jsonl | grep '"canary_status": "PASS"\|"canary_status":"PASS"' | tail -1 | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['docker_tag'])" 2>/dev/null || echo "UNKNOWN")
if [[ "$DOCKER_TAG" == "UNKNOWN" ]]; then
    echo "ERROR: No passing canary in manifest. Run safe_build_and_canary.sh first."
    exit 1
fi

STRATEGY=""
if $SPOT; then
    STRATEGY="
scheduling:
  strategy: SPOT"
fi

CONFIG_FILE="gcp/phase10_inference_config.yaml"

cat > "$CONFIG_FILE" << YAML
# AUTO-GENERATED by gen_inference_config.sh — DO NOT HAND-EDIT
# C-028: Local SSD enforced (4.8 GB/s, NOT pd-ssd)
# C-039: GPU auto-detect (torch.cuda.is_available)
# C-032: checkpoint_interval=${CKPT_INTERVAL} (never 0)
workerPoolSpecs:
- machineSpec:
    machineType: g2-standard-8
    acceleratorType: NVIDIA_L4
    acceleratorCount: 1
  replicaCount: 1
  diskSpec:
    bootDiskType: pd-ssd
    bootDiskSizeGb: 1300
  containerSpec:
    imageUri: ${DOCKER_TAG}
    command:
    - bash
    - -c
    - |
      set -e
      echo "=== Phase 10 Inference (gen_inference_config.sh) ==="

      # C-028: Use fastest available I/O. Vertex AI g2 has no Local SSD.
      # Options: (1) pre-mounted Local SSD (2) pd-ssd staging (3) FUSE direct
      echo "=== Stage 1: Stage shards ==="
      if [[ -d /mnt/disks/local-nvme-ssd ]]; then
        SHARD_DIR=/mnt/disks/local-nvme-ssd/shards
        echo "Using pre-mounted Local NVMe SSD"
      else
        SHARD_DIR=/tmp/shards
        echo "No Local SSD available on this machine type, using pd-ssd staging"
      fi
      mkdir -p \${SHARD_DIR}

      t0=\$(date +%s)
      gcloud storage cp "gs://omega-pure-data/wds_shards_v3_full/omega_shard_*.tar" \${SHARD_DIR}/ 2>&1 | tail -5
      t1=\$(date +%s)
      echo "Staged \$(ls \${SHARD_DIR}/*.tar | wc -l) shards in \$((t1-t0))s to \${SHARD_DIR}"

      echo "=== Stage 2: Inference (GPU auto-detect) ==="
      PYTHONUNBUFFERED=1 python3 /app/phase7_inference.py \\
        --checkpoint=${CHECKPOINT} \\
        --shard_dir=\${SHARD_DIR} \\
        --date_map=/gcs/omega-pure-data/phase7/shard_date_map.json \\
        --output=${OUTPUT} \\
        --hidden_dim=${HD} \\
        --window_size_t=${WT} \\
        --window_size_s=${WS} \\
        --batch_size=${BS} \\
        --checkpoint_interval=${CKPT_INTERVAL}

      echo "=== Stage 3: Verify ==="
      python3 -c "
      import pyarrow.parquet as pq
      t = pq.read_table('${OUTPUT}')
      print(f'Rows: {t.num_rows:,}')
      print(f'Columns: {t.column_names}')
      assert 'z_sparsity' in t.column_names, 'MISSING z_sparsity!'
      assert t.num_rows > 9_000_000, f'Too few rows: {t.num_rows}'
      for col in ['pred_bp', 'target_bp', 'z_sparsity']:
          assert t.column(col).null_count == 0, f'{col} has nulls!'
      print('INFERENCE_PASS')
      "
${STRATEGY}
YAML

echo "Generated: ${CONFIG_FILE}"
echo "  Docker: ${DOCKER_TAG}"
echo "  Checkpoint: ${CHECKPOINT}"
echo "  Output: ${OUTPUT}"
echo "  Model: hd=${HD} wt=${WT} ws=${WS}"
echo "  Strategy: $(if $SPOT; then echo SPOT; else echo ON-DEMAND; fi)"
echo ""
echo "Submit with: bash gcp/safe_submit.sh <phase> <version> ${CONFIG_FILE}"
